name: ssr_cli
description: CLI tools for SSR Framework
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.12.2

dependencies:
  args: ^2.4.0
  path: ^1.9.0
  io: ^1.0.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0

executables:
  ssr: ssr_cli
