name: ssr_router
description: File-based routing for SSR Framework
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.12.2

dependencies:
  ssr_core:
    path: ../ssr_core
  path: ^1.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
